# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='language',
            field=models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('it', 'it')], max_length=128),
        ),
    ]
