# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180127_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compound', models.FloatField()),
                ('neg', models.FloatField()),
                ('neu', models.FloatField()),
                ('pos', models.FloatField()),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Text')),
            ],
        ),
    ]
