# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sentimentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='facebook_id',
            field=models.CharField(max_length=255),
        ),
    ]
