# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('core', '0005_auto_20180127_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='entities',
            field=models.ManyToManyField(to='tags.Entity'),
        ),
        migrations.AddField(
            model_name='text',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='text',
            name='topics',
            field=models.ManyToManyField(to='tags.Topic'),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('fr', 'fr'), ('en', 'en'), ('it', 'it')], db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='text',
            name='facebook_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
