# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180128_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, verbose_name='source name'),
        ),
    ]
