# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180129_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='created_by',
        ),
    ]
