# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:41
from __future__ import unicode_literals

from django.db import migrations, models


def foward(apps, schema_editor):
    Text = apps.get_model('core', 'Text')
    for text in Text.objects.all():
        if text.source.language == 'en':
            text.is_translated = True
            text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180129_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='original_link_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='original_link_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='original_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='is_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(foward),
    ]
