# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180207_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(null=True, verbose_name='url of the media'),
        ),
    ]
