# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_source_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentimentreport',
            options={'ordering': ('text__created',)},
        ),
    ]
