# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180208_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable the collect of the posts and display the source on the site'),
        ),
    ]
