# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180307_1744'),
        ('tags', '0005_auto_20180308_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='text',
            name='topics',
        ),
    ]
