# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20180129_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('Anniversary', 'Anniversary'), ('City', 'City'), ('Company', 'Company'), ('Continent', 'Continent'), ('Country', 'Country'), ('Editor', 'Editor'), ('EmailAddress', 'EmailAddress'), ('EntertainmentAwardEvent', 'EntertainmentAwardEvent'), ('Facility', 'Facility'), ('FaxNumber', 'FaxNumber'), ('Holiday', 'Holiday'), ('IndustryTerm', 'IndustryTerm'), ('Journalist', 'Journalist'), ('MarketIndex', 'MarketIndex'), ('MedicalCondition', 'MedicalCondition'), ('MedicalTreatment', 'MedicalTreatment'), ('Movie', 'Movie'), ('MusicAlbum', 'MusicAlbum'), ('MusicGroup', 'MusicGroup'), ('NaturalFeature', 'NaturalFeature'), ('OperatingSystem', 'OperatingSystem'), ('Organization', 'Organization'), ('Person', 'Person'), ('PharmaceuticalDrug', 'PharmaceuticalDrug'), ('PhoneNumber', 'PhoneNumber'), ('PoliticalEvent', 'PoliticalEvent'), ('Position', 'Position'), ('Product', 'Product'), ('ProgrammingLanguage', 'ProgrammingLanguage'), ('ProvinceOrState', 'ProvinceOrState'), ('PublishedMedium', 'PublishedMedium'), ('RadioProgram', 'RadioProgram'), ('RadioStation', 'RadioStation'), ('Region', 'Region'), ('SportsEvent', 'SportsEvent'), ('SportsGame', 'SportsGame'), ('SportsLeague', 'SportsLeague'), ('Technology', 'Technology'), ('TVShow', 'TVShow'), ('TVStation', 'TVStation'), ('URL', 'URL')], db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('tag', 'tag'), ('entity', 'entity'), ('topic', 'topic')], db_index=True, default='tag', max_length=255),
        ),
    ]
