# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 10:18
from __future__ import unicode_literals

from django.db import migrations


def foward(apps, schema_editor):
    Entity = apps.get_model('tags', 'Entity')
    Topic = apps.get_model('tags', 'Topic')
    Tag = apps.get_model('tags', 'Tag')
    HighlightedTag = apps.get_model('highlights', 'HighlightedTag')
    for entity in Entity.objects.all():
        tag = Tag.objects.create(
            name=entity.name,
            tag_type='entity',
            entity_type=entity.entity_type,
        )
        tag.text_set.set(entity.text_set.all())
        highlighted = entity.highlightedentity_set.all().first()
        if highlighted:
            HighlightedTag.objects.create(tag=tag, order=highlighted.order)
    for topic in Topic.objects.all():
        tag = Tag.objects.create(
            name=topic.name,
            tag_type='topic',
        )
        tag.text_set.set(topic.text_set.all())


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20180308_1018'),
        ('highlights', '0003_highlightedtag'),
    ]

    operations = [
        migrations.RunPython(foward),
    ]
