# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20180308_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
