# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_tag_hide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
