# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightedentity',
            options={'ordering': ['order'], 'verbose_name_plural': 'Highlighted Entities'},
        ),
    ]
