# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_highlightedtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightedentity',
            name='entity',
        ),
        migrations.DeleteModel(
            name='HighlightedEntity',
        ),
    ]
